"""initial schema

Revision ID: 4496d06107f6
Revises: 
Create Date: 2026-02-18 11:21:11.183861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4496d06107f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('representante', sa.String(length=190), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=190), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academias_nombre'), ['nombre'], unique=True)

    op.create_table('categorias_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('edad_min', sa.Integer(), nullable=True),
    sa.Column('edad_max', sa.Integer(), nullable=True),
    sa.Column('peso_min', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('peso_max', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_competencia_nombre'), ['nombre'], unique=False)

    op.create_table('divisiones_poomsae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('nivel', sa.String(length=30), nullable=True),
    sa.Column('edad_min', sa.Integer(), nullable=True),
    sa.Column('edad_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('numeradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_doc', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=False),
    sa.Column('ultimo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_doc', 'serie', name='uq_numerador_tipo_serie')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rubros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('productos_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('requiere_categoria', sa.Boolean(), nullable=False),
    sa.Column('requiere_dan', sa.Boolean(), nullable=False),
    sa.Column('requiere_division_poomsae', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos_servicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_servicio_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_servicio_rubro_id'), ['rubro_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(length=190), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_producto_id'), ['producto_id'], unique=False)

    op.create_table('evento_categorias_habilitadas',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'categoria_id')
    )
    op.create_table('evento_divisiones_poomsae',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('division_poomsae_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_poomsae_id'], ['divisiones_poomsae.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('evento_id', 'division_poomsae_id')
    )
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descuentos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id', 'academia_id', name='uq_inscripcion_evento_academia')
    )
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripciones_academia_id'), ['academia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripciones_evento_id'), ['evento_id'], unique=False)

    op.create_table('tarifas_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('tipo_calculo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarifas_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarifas_evento_evento_id'), ['evento_id'], unique=False)

    op.create_table('documentos_cobro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_al_emitir', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'serie', 'numero', name='uq_documento_numero')
    )
    with op.batch_alter_table('documentos_cobro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_cobro_inscripcion_id'), ['inscripcion_id'], unique=False)

    op.create_table('inscripcion_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('division_poomsae_id', sa.Integer(), nullable=True),
    sa.Column('dan_nivel', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['division_poomsae_id'], ['divisiones_poomsae.id'], ),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inscripcion_id', 'modalidad', 'categoria_id', 'division_poomsae_id', 'dan_nivel', name='uq_detalle_inscripcion_dimensiones')
    )
    with op.batch_alter_table('inscripcion_detalles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inscripcion_detalles_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripcion_detalles_division_poomsae_id'), ['division_poomsae_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inscripcion_detalles_inscripcion_id'), ['inscripcion_id'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inscripcion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=30), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('comprobante_path', sa.String(length=255), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inscripcion_id'], ['inscripciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_inscripcion_id'), ['inscripcion_id'], unique=False)

    op.create_table('tarifas_evento_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarifa_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('division_poomsae_id', sa.Integer(), nullable=True),
    sa.Column('dan_nivel', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['division_poomsae_id'], ['divisiones_poomsae.id'], ),
    sa.ForeignKeyConstraint(['tarifa_id'], ['tarifas_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarifas_evento_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_division_poomsae_id'), ['division_poomsae_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_id'), ['tarifa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_evento_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_id'))
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_division_poomsae_id'))
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_categoria_id'))

    op.drop_table('tarifas_evento_detalle')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_inscripcion_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('inscripcion_detalles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripcion_detalles_inscripcion_id'))
        batch_op.drop_index(batch_op.f('ix_inscripcion_detalles_division_poomsae_id'))
        batch_op.drop_index(batch_op.f('ix_inscripcion_detalles_categoria_id'))

    op.drop_table('inscripcion_detalles')
    with op.batch_alter_table('documentos_cobro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_cobro_inscripcion_id'))

    op.drop_table('documentos_cobro')
    with op.batch_alter_table('tarifas_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_evento_id'))

    op.drop_table('tarifas_evento')
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inscripciones_evento_id'))
        batch_op.drop_index(batch_op.f('ix_inscripciones_academia_id'))

    op.drop_table('inscripciones')
    op.drop_table('evento_divisiones_poomsae')
    op.drop_table('evento_categorias_habilitadas')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_producto_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_nombre'))
        batch_op.drop_index(batch_op.f('ix_eventos_anio'))

    op.drop_table('eventos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('productos_servicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_servicio_rubro_id'))
        batch_op.drop_index(batch_op.f('ix_productos_servicio_nombre'))

    op.drop_table('productos_servicio')
    op.drop_table('rubros')
    op.drop_table('roles')
    op.drop_table('numeradores')
    op.drop_table('divisiones_poomsae')
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_competencia_nombre'))

    op.drop_table('categorias_competencia')
    with op.batch_alter_table('academias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academias_nombre'))

    op.drop_table('academias')
    # ### end Alembic commands ###
