"""add descripcion and activo to tarifas_evento

Revision ID: ab22e1aceab2
Revises: 08cb44a57576
Create Date: 2026-03-13 21:37:29.123837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab22e1aceab2'
down_revision = '08cb44a57576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_eventos')
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('sede',
               existing_type=sa.VARCHAR(length=190),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_eventos_nombre'))

    with op.batch_alter_table('tarifas_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=190),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('tipo_calculo')
        batch_op.drop_column('valor')
        batch_op.drop_column('vigencia_hasta')
        batch_op.drop_column('prioridad')
        batch_op.drop_column('vigencia_desde')

    with op.batch_alter_table('tarifas_evento_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarifa_evento_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('concepto', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_division_poomsae_id'))
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_id'))
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_evento_id'), ['tarifa_evento_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tarifas_evento', ['tarifa_evento_id'], ['id'])
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('tarifa_id')
        batch_op.drop_column('dan_nivel')
        batch_op.drop_column('division_poomsae_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_evento_detalle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_poomsae_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dan_nivel', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tarifa_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('categoria_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tarifas_evento', ['tarifa_id'], ['id'])
        batch_op.create_foreign_key(None, 'categorias_competencia', ['categoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'divisiones_poomsae', ['division_poomsae_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_evento_id'))
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_tarifa_id'), ['tarifa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_division_poomsae_id'), ['division_poomsae_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarifas_evento_detalle_categoria_id'), ['categoria_id'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('concepto')
        batch_op.drop_column('tarifa_evento_id')

    with op.batch_alter_table('tarifas_evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vigencia_desde', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('prioridad', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('vigencia_hasta', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tipo_calculo', sa.VARCHAR(length=30), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=190),
               existing_nullable=False)
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_nombre'), ['nombre'], unique=False)
        batch_op.alter_column('sede',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=190),
               existing_nullable=True)

    op.create_table('_alembic_tmp_eventos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=190), nullable=False),
    sa.Column('anio', sa.INTEGER(), nullable=False),
    sa.Column('sede', sa.VARCHAR(length=150), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=True),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('valor_base', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
